steps:
  # Download and package model
  - name: "python:3.10"
    entrypoint: pip
    args:
      [
        "install",
        "--user",
        "--no-cache-dir",
        "-r",
        "models/types/huggingface/requirements.txt",
        "-v",
      ]

  - name: "python:3.10"
    entrypoint: python
    args:
      - -c
      - |
        import transformers
        from transformers import AutoModel, AutoTokenizer

        model = AutoModel.from_pretrained('${_MODEL_ID}')
        tokenizer = AutoTokenizer.from_pretrained('${_MODEL_ID}')

        model.save_pretrained('/workspace/model')
        tokenizer.save_pretrained('/workspace/model')

        with tarfile.open('model.tar.gz', 'w:gz') as tar:
            tar.add('/workspace/model', arcname='.')
    env:
      - "HUGGING_FACE_TOKEN=${_HF_TOKEN}"

  # Build and push predictor container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ENVIRONMENT}-vertex-ai-repo/${_MODEL_ID}",
        "-f",
        "models/types/huggingface/docker/Dockerfile",
        "--build-arg",
        "HF_TASK=${_HF_TASK}",
        "models/types/huggingface/docker",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ENVIRONMENT}-vertex-ai-repo/${_MODEL_ID}",
      ]

  # Deploy to Vertex AI
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        # Upload model artifacts
        gsutil cp model.tar.gz gs://$PROJECT_ID-${_ENVIRONMENT}-models/${_MODEL_ID}/

        # Deploy to endpoint
        gcloud ai models upload \
          --region=${_REGION} \
          --display-name=${_MODEL_ID} \
          --artifact-uri=gs://$PROJECT_ID-${_ENVIRONMENT}-models/${_MODEL_ID} \
          --container-image-uri=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ENVIRONMENT}-vertex-ai-repo/${_MODEL_ID} \
          --container-env-vars=HF_TASK=${_HF_TASK}

        gcloud ai endpoints deploy-model ${_ENDPOINT} \
          --region=${_REGION} \
          --model=${_MODEL_ID} \
          --machine-type=n1-standard-4 \
          --min-replica-count=1 \
          --max-replica-count=1

timeout: "3600s"

options:
  logging: CLOUD_LOGGING_ONLY
