# environment.yml
name: sign_language_chat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - opencv
  - pillow>=9.0.0
  - pip:
    - mediapipe
    - gradio>=5.6.0
