steps:
  # Validate model artifacts
  - name: "python:3.9"
    entrypoint: python
    args:
      - -c
      - |
        import torch
        from transformers import WhisperForConditionalGeneration
        model = WhisperForConditionalGeneration.from_pretrained('${_MODEL_PATH}')
        torch.save(model.state_dict(), '/workspace/model.pt')

  # Upload to GCS
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - -m
      - cp
      - -r
      - "/workspace/model.pt"
      - "gs://${_BUCKET_NAME}/${_MODEL_VERSION}/"

  # Deploy using Terraform
  - name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - -c
      - |
        cd terraform/environments/${_ENVIRONMENT}
        terraform init
        terraform apply -auto-approve \
          -var="model_version=${_MODEL_VERSION}" \
          -var="environment=${_ENVIRONMENT}"

substitutions:
  _ENVIRONMENT: "staging" # default value
  _MODEL_VERSION: "v1" # default value
  _MODEL_PATH: "" # must be provided
  _BUCKET_NAME: "" # must be provided
